<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Piootoo.Sweep</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>piootoo-sweep</AssemblyName>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Piootoo.Core\Piootoo.Core.csproj" />
    <ProjectReference Include="..\Piootoo.Strategies\Piootoo.Strategies.csproj" />
  </ItemGroup>

</Project>
