<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Piootoo.PlanBuilder</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>piootoo-plan-builder</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Piootoo.Core\Piootoo.Core.csproj" />
  </ItemGroup>

</Project>
